name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v1
    - name: Compile the sketch # TODO: https://github.com/arduino/compile-sketches/issues/25
      uses: arduino/compile-sketches@v1 # https://github.com/arduino/compile-sketches
      with:
        sketch-paths: |
          - .
    - uses: actions/setup-node@v2
      with:
        node-version: 16 # https://github.com/actions/setup-node/issues/257
    - name: Validate expected output
      run: |
        set -e
        set -x

        # Copy the HEX over to the working directory
        cp /tmp/arduino-sketch-*/arduino-nmea.ino.hex arduino-nmea.hex

        # Install NPM dependencies (avr8js)
        npm install

        # Run the script to run the sketch using Wokwi
        node .

        # Check if the produced file matches the expected file
        diff nmea-checksum.uart nmea-checksum.uart.test
