name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install latest Arduino CLI
      uses: arduino/actions/setup-arduino-cli@master
    - name: Validate expected output
      run: |
        set -x
        # Update index, install the AVR core and compile the sketch (into ELF and HEX) for the Uno
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli compile -b arduino:avr:uno nmea-checksum.ino
        # Install dependencies for building SimAVR
        sudo apt-get update
        sudo apt-get install -y build-essential libelf-dev avr-libc gcc-avr freeglut3-dev libncurses5-dev pkg-config
        # Clone the SimAVR repo and build it
        git clone https://github.com/buserror/simavr.git
        cd simavr
        make
        # Go to the compiled artifacts where `run_avr` is now
        cd simavr
        # Start the simulation with a timeout of 10 seconds (because of the infinite loop)
        timeout 10 ./run_avr -m atmega168 -f 16000000 ../../nmea-checksum.ino.arduino.avr.uno.elf 2> nmea-checksum.ino.clog || true
        # Strip ANSI color codes from the output
        cat nmea-checksum.ino.clog | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" > nmea-checksum.ino.log
        cat nmea-checksum.ino.log
        # Check if the produced file matches the expected file
        diff nmea-checksum.ino.log ../../nmea-checksum.ino.test
    - name: Try using the Arduino Builder
      continue-on-error: true
      run: |
        set -x
        version=1.5.0
        # Download and extract the Arduino Builder
        curl -L -o arduino-builder-${version}.tar.xz https://github.com/arduino/arduino-builder/releases/download/${version}/arduino-builder-${version}.tar.xz
        tar -xvf arduino-builder-${version}.tar.xz
        # Install Go dependencies and build the executable
        go get github.com/go-errors/errors
        go get github.com/stretchr/testify
        go get github.com/jstemmer/go-junit-report
        go get -u github.com/arduino/go-paths-helper
        go get -u github.com/arduino/go-properties-orderedmap
        go get -u github.com/arduino/go-timeutils
        go get google.golang.org/grpc
        go get github.com/golang/protobuf/proto
        go get golang.org/x/net/context
        go get github.com/fsnotify/fsnotify
        go get github.com/schollz/closestmatch
        go get github.com/arduino/arduino-builder
        go build github.com/arduino/arduino-builder/arduino-builder
        # TODO
        ls
