name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v1
    - name: Compile the sketch # TODO: Figure out how to get the HEX from this
      uses: arduino/compile-sketches@v1 # https://github.com/arduino/compile-sketches
      with:
        sketch-paths: |
          - .
        cli-compile-flags: |
          - --output-dir="$PWD" # TODO: Figure out why this didn't work
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1 # https://github.com/arduino/setup-arduino-cli
    - name: Validate expected output
      run: |
        set -e
        set -x
        cp /tmp/arduino-sketch-*/arduino-nmea.ino.hex arduino-nmea.hex
        cat arduino-nmea.hex
        # TODO: Run https://github.com/TomasHubelbauer/wokwi-nmea-checksum
        # Check if the produced file matches the expected file
        diff nmea-checksum.uart nmea-checksum.uart.check
