name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Validate expected output
      run: |
        set -x
        # Download and install the latest Arduino CLI
        mkdir -p /home/runner/work/arduino-nmea-checksum/arduino-nmea-checksum/bin
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/home/runner/work/arduino-nmea-checksum/arduino-nmea-checksum/bin sh
        # Update index, install the AVR core and compile the sketch (into ELF and HEX) for the Uno
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli compile -b arduino:avr:uno nmea-checksum.ino
        # Install dependencies for building SimAVR
        sudo apt-get update
        sudo apt-get install -y build-essential libelf-dev avr-libc gcc-avr freeglut3-dev libncurses5-dev pkg-config
        # Close the SimAVR repo and build it
        git clone https://github.com/buserror/simavr.git
        cd simavr
        make
        # Go to the compiled artifacts where `run_avr` is now
        cd simavr
        # Start the simulation with a timeout of 10 seconds (because of the infinite loop)
        timeout 10 ./run_avr -m atmega168 -f 16000000 ../../nmea-checksum.ino.arduino.avr.uno.elf &> nmea-checksum.ino.clog || true
        # Strip ANSI color codes from the output
        cat nmea-checksum.ino.clog | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g" > nmea-checksum.ino.log
        cat nmea-checksum.ino.log
        # Check if the produced file matches the expected file
        diff nmea-checksum.ino.log ../../nmea-checksum.ino.test
