name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v1
    - name: Compile the sketch # TODO: https://github.com/arduino/compile-sketches/issues/25
      uses: arduino/compile-sketches@v1 # https://github.com/arduino/compile-sketches
      with:
        sketch-paths: |
          - .
    - name: Copy the HEX from a temporary directory over to the working directory
      run: cp /tmp/arduino-sketch-*/arduino-nmea.ino.hex arduino-nmea.hex
    - uses: actions/upload-artifact@v2
      with:
        name: arduino-nmea.hex
        path: arduino-nmea.hex
    - name: Use latest Node 16 with top-level await support
      uses: actions/setup-node@v2
      with:
        node-version: 16 # https://github.com/actions/setup-node/issues/257
    - name: Validate expected output
      run: |
        set -e
        set -x

        # Install NPM dependencies (avr8js)
        npm install

        # Run the script to run the sketch using Wokwi
        node .

        # Check if the produced file matches the expected file
        diff arduino-nmea.uart arduino-nmea.uart.test
