name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v1
    - name: Compile the sketch # TODO: Figure out how to get the HEX from this
      uses: arduino/compile-sketches@v1 # https://github.com/arduino/compile-sketches
      with:
        sketch-paths: |
          - .
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1.1.1 # https://github.com/arduino/setup-arduino-cli
    - name: Validate expected output
      run: |
        set -e
        set -x
        # Update index, install the AVR core and compile the sketch (into ELF and HEX) for the Uno
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli compile -b arduino:avr:uno nmea-checksum
        # Check if the produced file matches the expected file
        diff nmea-checksum.ino.uart nmea-checksum.ino.test
